# GitHub Actions workflow to build and push a Docker image.
#
# This workflow is triggered on pushes to the 'main' branch and any branch
# under 'support/'. It builds a Docker image from the Dockerfile in the root
# of the repository and pushes it to the GitHub Container Registry (ghcr.io).

name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'support/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry. 
      # You can replace this with a login to another registry like Docker Hub or ACR.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extracts metadata (tags, labels) for the Docker image.
      # This will generate tags like 'latest' for the main branch,
      # the branch name for support branches, and the git SHA.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # Build and push the Docker image to the registry.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
